# Generated by Django 2.2.4 on 2019-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_open_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_featured',
            field=models.BooleanField(default=False),
        ),
    ]
