# Generated by Django 2.2.4 on 2019-08-22 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
