# Generated by Django 2.2.4 on 2019-08-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
