# Generated by Django 2.2.4 on 2019-08-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190831_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_client_website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
