# Generated by Django 2.2.4 on 2019-09-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190831_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='project_overview',
        ),
    ]
