# Generated by Django 2.2.4 on 2019-08-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blog')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_text', models.TextField()),
                ('blog_date', models.DateTimeField()),
            ],
        ),
    ]
