# Generated by Django 2.2.4 on 2019-08-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190813_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
