# Generated by Django 3.0 on 2020-10-26 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='skills')),
                ('timestamp', models.DateField(default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('LANGUAGES', 'Languages'), ('FRAMEWORKS_AND_LIBRARIES', 'Frameworks & libraries'), ('DATABASE', 'Database'), ('OTHER_TECHNOLOGIES', 'Other Technologies')], max_length=255)),
            ],
        ),
    ]
